config/routes.rb
# Rails.application.routes.draw do
#   root to: 'users#index'
#   devise_for :users

#   get '/users/', to: 'users#index'
#   get '/users/:id/', to: 'users#show'

#   get '/posts/new', to: 'posts#new'
#   get '/users/:id/posts/', to: 'posts#index'
#   get '/users/:id/posts/:id/', to: 'posts#show'

#   post '/posts', to: 'posts#create'
#   post '/users/:user_id/posts/:id/comments', to: 'comments#create'
#   post '/users/:user_id/posts/:id/likes', to: 'likes#create'
# end

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  get '/users/', to: 'users#index'
  get '/users/:id/', to: 'users#show'

  get '/posts/new', to: 'posts#new'
  get '/users/:user_id/posts/', to: 'posts#index'
  get '/users/:user_id/posts/:id/', to: 'posts#show'

  post '/posts', to: 'posts#create'
  post '/users/:user_id/posts/:id/comments', to: 'comments#create'
  post '/users/:user_id/posts/:id/likes', to: 'likes#create'
  delete '/users/:user_id/posts/:id', to: 'posts#destroy'
  delete '/users/:user_id/posts/:post_id/comments/:id', to: 'comments#destroy'

  namespace :api, defaults: { format: :json } do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index show] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :destroy, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'Users'
  belongs_to :post

  after_save :update_likess_counter

  def update_likess_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def display_comments
    comments.limit(5).order(created_at: :desc)
  end

  after_save :update_posts_counter_add

  def update_posts_counter_add
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def display_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = current_user.comments.new(comment_params)
    @post = Post.find(params[:id])
    @comment.post_id = @post.id

    if @comment.save
      flash[:success] = 'Comment created successfully'
      redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
    else
      flash.now[:error] = 'Error: Comment could not be ccreated!!'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def destroy
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to comments_path, notice: 'Comment was successfully deleted.'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @post = Post.find(params[:id])
    @like.post_id = @post.id

    if @like.save
      flash[:success] = 'Like Pressed'
      redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
    else
      flash.now[:error] = 'Error : like could not be created'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:id])
    @userposts = @user.posts.includes(:comments)
    render json: @posts, status: :ok
  end

  def show
    @post = Post.find(params[:id])
    render json: @posts, status: :ok
    @current_user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
    else
      flash.now[:error] = 'Error: Post could not be created!!'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def destroy
    authorize! :destroy, @post
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!
  def index
    @users = User.all

    render json: @users, status: :ok
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "application"%>

<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <p class="notice"><%= notice %> </p>
    <p class="alert"><%= alert %> </p>

    
  <% if user_signed_in? %><%= stylesheet_link_tag "application"%>
      <button class="mybtn2" type="button"><%= link_to "Sign out", destroy_user_session_path, method: :DELETE %><button>
   <% end %> 
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "application"%>

<div class="all_users"> 
    <h1>Posts by a User</h1>
    <div class="user-container">
        <img src=" <%= @user.photo %>" alt="User profile" width="130" height="130"><br>
            <div class="single-user">
                <h2>User Name:  <%= @user.name %></h2><br>
                <div class="single-user-insider">
                 <p>No.of Posts: <%= @user.posts_counter %></p><br>
                </div>
            </div>
    </div>    
</div>
<% @userposts.each do |post| %>
    <div class="particular_user">
        <h3>Post #<%= post.id %></h3><br>
        <p><%= post.text %></p><br>
        <div class="user-com-likes">
            <p>Comments: <%= post.comments_counter %>, </p>
            <p>Likes: <%= post.likes_counter %></p>
            <%= form_with model: @like, url: "/users/#{@user.id}/posts/#{post.id}/likes" do |form| %>
            <% form.submit "👍🏻" %>
        <% end %>
        </div>
    </div> 
    <div class="particular_user">
     <%= post.display_comments.each do |comment| %> 
        <p><%= comment.author.name %> : <%= comment.text %> </p>
     <% end %>

     <h3>Add a comment: </h3>
        <%= form_with model: @comment, url: "/users/#{@user.id}/posts/#{post.id}/comments" do |form| %>
            <%= form.text_area :text,  placeholder: "Add a comment" %>
            <%= form.submit "submit" %>
        <% end %>
        </div>

     </div>   
<% end %>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger Posts</title>
  <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
</head>
<body>
   <div class="container">
      <h2> create a post </h2>
   <%= form_with model: @post, url: "/posts" do |form| %>
    <div class="form">
    <%= form.text_field :title, placeholder: "title", class: "field" %>
    <%= form.text_area :text,  placeholder: "Add a post", class: "field" %>
    <%= form.submit "submit", class: "btn" %>
    </div>
    <% end %>
  </div>
</body>
</html>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "application"%>

<div class="all_users">
    <h1>A particular post</h1>
    <div class="user-container">
            <div class="single-post">
                    <div class ="single-post-top">
                        <p>Post #<%= @post.id %> by: <%= @post.author.name %></p><br>
                        <div class="single-post-top-content">
                            <p>Comments: <%= @post.comments_counter %></p>,
                            <p>Likes: <%= @post.likes_counter %></p><br>
                        </div>
                    </div>
                <p><%= @post.text %></p><br>
            </div>
    </div>
</div>

<div class="all-coments-in-posts-outer">
    <% @post.display_comments.each do |comment| %>
        <div class="all-coments-in-posts">
                <p><%= comment.author.name %>: </p>
                <p><%= comment.text %></p>
            </div>
            <% if can? :destroy, @post %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
<% end %>
<% @comments.each do |comment| %>
  <% if can? :destroy, comment %>
    <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
  <% end %>
<% end %>

<% end %>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Platfom Blog Posts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
</head>
<body>
    <section class="users_list">
    <h1>The Users List</h1>
    <div class="Add-post">
      <a href=<%="/posts/new" %>>Add a new post</a>
  </div>
    <% @users.each do |user| %>
    <div class="users">
      <div class="user_image">
        <img class="img" src=<%= user.photo %> alt="user image" />
      </div> 
         <a href=<%= "/users/#{user.id}" =%> >
         <div class="info">
           <p class="user_name"> <%= user.name %> </p>
            <span class="number_posts"> Number of posts : <%= "#{user.posts_counter || 0}" %> <span>
         </div>
         </a>
     </div>
     <% end %>
     </section>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Platform Blog Posts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
</head>
<body>

<section class="container">

 <div class="users_list">
    <h1>Here is a User</h1>
    <div class="users user-post">
       <div class="user_image">
          <img class="img" src="#{@user.photo}" alt="user image" />
          <a href=<%= "/users/#{@user.id}/posts/" %> >
            </div> 
                <div class="info">
                  <p  class="user_name"> <%= @user.name %> </p>
                  <span class="number_posts"> Number of posts : <%= "#{@user.posts_counter || 0}" %> <span>
                </div>
            </div> 
            </a>
       </div>

       <div class="bio">
          <h2>Bio </h2>
         <p class="post-text"><%= @user.bio %> </p>
       </div>
    </div>
    <div class="posts">
    <%  @user.display_posts.each do |post| %>
      <a href=<%= "/users/#{@user.id}/posts/#{post.id}" %> >
       <h3> PostNo <%= post.id %> </h3>
       <div class="wrap-post">
       <p class="post-text"> <%= post.text %> </p>
       <div class="comments-likes">
         <span>Comments: <%= "#{post.comments_counter || 0}" %> </span>
         <span> Likes: <%= "#{post.likes_counter || 0}" %> </span>
      </div>
      </div>
      </a>
     <% end %>
       <a class="see-posts" href=<%="/users/#{@user.id}/posts" %> > See All Posts </a>
     </div>

 </section>
</body>
</html>